(function(){
  const KEY='pcc-web-v6';
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const save=d=>localStorage.setItem(KEY,JSON.stringify(d));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const todayKey=()=>{const n=new Date();return `${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`};
  let cursor=new Date(new Date().getFullYear(),new Date().getMonth(),1), selected=todayKey();
  function ensure(){const d=load();if(!Array.isArray(d.events))d.events=[];save(d);return d}
  function addUI(){
    if(!document.querySelector('nav [data-s="calendar"]')){const money=document.querySelector('nav [data-s="money"]');const b=document.createElement('button');b.dataset.s='calendar';b.innerHTML='📅<br>Calendar';b.onclick=()=>{window.show?.('calendar');renderCalendar()};if(money)money.after(b);else document.querySelector('nav')?.append(b)}
    if(!document.getElementById('calendar')){const main=document.querySelector('main');if(!main)return;const sec=document.createElement('section');sec.id='calendar';sec.className='screen';sec.innerHTML=`<div class="title"><h2>📅 Calendar</h2><button class="primary" id="tendAddEvent">+ Event</button></div><div class="tend-cal-head"><button id="tendPrev">‹</button><div id="tendCalTitle"></div><button id="tendNext">›</button></div><div id="tendCalGrid" class="tend-cal-grid"></div><div class="sectionHead"><h3 id="tendSelectedTitle">Events</h3><button class="link" id="tendAddEvent2">+ Add</button></div><div id="tendEventList"></div>`;main.insertBefore(sec,main.querySelector('#care'));document.getElementById('tendPrev').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);renderCalendar()};document.getElementById('tendNext').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);renderCalendar()};document.getElementById('tendAddEvent').onclick=()=>eventForm();document.getElementById('tendAddEvent2').onclick=()=>eventForm()}
  }
  function eventForm(date){const d=ensure(),dt=date||selected;if(window.open)window.open(`<h2>📅 Add calendar event</h2><label>Event<input id="tendEventName" placeholder="Vet appointment, farrier, feeding..."></label><div class="formgrid"><label>Date<input id="tendEventDate" type="date" value="${dt}"></label><label>Time<input id="tendEventTime" type="time"></label></div><label>Animal (optional)<select id="tendEventPet"><option value="">Household / facility</option>${(d.pets||[]).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Notes<textarea id="tendEventNotes" placeholder="Details, location, reminders..."></textarea></label><button class="primary" onclick="window.tendSaveEvent()">Save event</button>`)}
  window.tendSaveEvent=function(){const d=ensure(),title=document.getElementById('tendEventName')?.value.trim();if(!title)return alert('Give the event a name first.');const date=document.getElementById('tendEventDate')?.value||selected;d.events.push({id:Date.now(),title,date,time:document.getElementById('tendEventTime')?.value||'',pet:document.getElementById('tendEventPet')?.value?Number(document.getElementById('tendEventPet').value):null,notes:document.getElementById('tendEventNotes')?.value||''});save(d);selected=date;const dt=new Date(date+'T12:00');cursor=new Date(dt.getFullYear(),dt.getMonth(),1);window.closeM?.();renderCalendar()};
  window.tendDeleteEvent=function(id){if(!confirm('Delete this calendar event?'))return;const d=ensure();d.events=d.events.filter(e=>e.id!==id);save(d);renderCalendar()};
  function renderCalendar(){addUI();const d=ensure(),y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7,total=Math.ceil((start+last.getDate())/7)*7,title=document.getElementById('tendCalTitle'),grid=document.getElementById('tendCalGrid');if(!title||!grid)return;title.textContent=cursor.toLocaleString(undefined,{month:'long',year:'numeric'});let h=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="tend-cal-dow">${x}</div>`).join('');for(let i=0;i<total;i++){const day=i-start+1,dt=new Date(y,m,day),inMonth=day>=1&&day<=last.getDate(),key=`${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`,ev=(d.events||[]).filter(e=>e.date===key).sort((a,b)=>(a.time||'').localeCompare(b.time||''));h+=`<button class="tend-cal-day ${inMonth?'':'mutedDay'} ${key===todayKey()?'today':''}" onclick="window.tendSelectDate('${key}')"><b>${dt.getDate()}</b><span>${ev.slice(0,3).map(e=>`<i>${esc(e.title)}</i>`).join('')}${ev.length>3?`<i>+${ev.length-3} more</i>`:''}</span></button>`}grid.innerHTML=h;renderEvents(d)}
  window.tendSelectDate=function(key){selected=key;const dt=new Date(key+'T12:00');cursor=new Date(dt.getFullYear(),dt.getMonth(),1);renderCalendar()};
  function renderEvents(d){const box=document.getElementById('tendEventList'),head=document.getElementById('tendSelectedTitle');if(!box||!head)return;head.textContent=new Date(selected+'T12:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});const list=(d.events||[]).filter(e=>e.date===selected).sort((a,b)=>(a.time||'').localeCompare(b.time||''));box.innerHTML=list.map(e=>`<div class="card tend-event"><div class="tend-event-time">${e.time||'All day'}</div><div style="flex:1"><b>${esc(e.title)}</b><div class="muted">${e.pet?esc((d.pets||[]).find(p=>p.id===e.pet)?.name||'Animal'):'Household / facility'}${e.notes?' · '+esc(e.notes):''}</div></div><button onclick="window.tendDeleteEvent(${e.id})">Delete</button></div>`).join('')||'<div class="empty">No events on this date. Add one with + Event. 📅</div>'}
  function fixCare(){const d=load();document.querySelectorAll('#careList .card.task .check').forEach((b,i)=>{if(d.care?.[i]){b.dataset.careId=d.care[i].id;b.setAttribute('onclick',`window.tendToggleCare(${d.care[i].id})`)}})}
  window.tendToggleCare=function(id){const d=load(),t=(d.care||[]).find(x=>x.id==id);if(!t)return;t.done=!t.done;save(d);window.render?.();setTimeout(fixCare,0)};
  function boot(){addUI();ensure();fixCare();renderCalendar();const care=document.getElementById('careList');if(care)new MutationObserver(()=>fixCare()).observe(care,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();