(function(){
  const KEY='pcc-web-v6';
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const save=d=>localStorage.setItem(KEY,JSON.stringify(d));
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const todayKey=()=>{const n=new Date();return `${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`};
  let cursor=new Date(new Date().getFullYear(),new Date().getMonth(),1),selected=todayKey();
  function ensure(){const d=load();if(!Array.isArray(d.events))d.events=[];if(!Array.isArray(d.expenses))d.expenses=[];if(!Array.isArray(d.care))d.care=[];save(d);return d}
  function goCalendar(){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));document.getElementById('calendar')?.classList.add('on');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.s==='calendar'));window.scrollTo(0,0);renderCalendar()}
  function addUI(){
    if(!document.getElementById('tendNavStyle')){const s=document.createElement('style');s.id='tendNavStyle';s.textContent='nav#nav{width:100%;overflow:hidden}nav#nav button{flex:1 1 0;min-width:0;padding-left:2px;padding-right:2px;font-size:10px;white-space:nowrap}nav#nav button br{display:block}@media(min-width:600px){nav#nav button{font-size:11px;padding-left:5px;padding-right:5px}}';document.head.append(s)}
    if(!document.querySelector('nav [data-s="calendar"]')){const money=document.querySelector('nav [data-s="money"]');const b=document.createElement('button');b.dataset.s='calendar';b.innerHTML='📅<br>Calendar';b.onclick=goCalendar;if(money)money.after(b);else document.querySelector('nav')?.append(b)}
    if(!document.getElementById('calendar')){const main=document.querySelector('main');if(!main)return;const sec=document.createElement('section');sec.id='calendar';sec.className='screen';sec.innerHTML=`<div class="title"><h2>📅 Calendar</h2><button class="primary" id="tendAddEvent">+ Event</button></div><div class="tend-cal-head"><button id="tendPrev">‹</button><div id="tendCalTitle"></div><button id="tendNext">›</button></div><div id="tendCalGrid" class="tend-cal-grid"></div><div class="sectionHead"><h3 id="tendSelectedTitle">Events</h3><button class="link" id="tendAddEvent2">+ Add</button></div><div id="tendEventList"></div>`;main.insertBefore(sec,main.querySelector('#care'));document.getElementById('tendPrev').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);renderCalendar()};document.getElementById('tendNext').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);renderCalendar()};document.getElementById('tendAddEvent').onclick=()=>eventForm();document.getElementById('tendAddEvent2').onclick=()=>eventForm()}
  }
  function eventForm(date){const d=ensure(),dt=date||selected,modal=document.getElementById('modal'),body=document.getElementById('body');if(!modal||!body)return;body.innerHTML=`<h2>📅 Add calendar event</h2><label>Event<input id="tendEventName" placeholder="Vet appointment, farrier, feeding..."></label><div class="formgrid"><label>Date<input id="tendEventDate" type="date" value="${dt}"></label><label>Time<input id="tendEventTime" type="time"></label></div><label>Animal (optional)<select id="tendEventPet"><option value="">Household / facility</option>${(d.pets||[]).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Notes<textarea id="tendEventNotes" placeholder="Details, location, reminders..."></textarea></label><button class="primary" onclick="window.tendSaveEvent()">Save event</button>`;modal.classList.add('on')}
  window.tendSaveEvent=function(){const d=ensure(),title=document.getElementById('tendEventName')?.value.trim();if(!title)return alert('Give the event a name first.');const date=document.getElementById('tendEventDate')?.value||selected;d.events.push({id:Date.now(),title,date,time:document.getElementById('tendEventTime')?.value||'',pet:document.getElementById('tendEventPet')?.value?Number(document.getElementById('tendEventPet').value):null,notes:document.getElementById('tendEventNotes')?.value||''});save(d);selected=date;const dt=new Date(date+'T12:00');cursor=new Date(dt.getFullYear(),dt.getMonth(),1);document.getElementById('modal')?.classList.remove('on');renderCalendar();refreshDashboard()};
  window.tendDeleteEvent=function(id){if(!confirm('Delete this calendar event?'))return;const d=ensure();d.events=d.events.filter(e=>e.id!==id);save(d);renderCalendar();refreshDashboard()};
  function renderCalendar(){addUI();const d=ensure(),y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7,total=Math.ceil((start+last.getDate())/7)*7,title=document.getElementById('tendCalTitle'),grid=document.getElementById('tendCalGrid');if(!title||!grid)return;title.textContent=cursor.toLocaleString(undefined,{month:'long',year:'numeric'});let h=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="tend-cal-dow">${x}</div>`).join('');for(let i=0;i<total;i++){const day=i-start+1,dt=new Date(y,m,day),inMonth=day>=1&&day<=last.getDate(),key=`${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`,ev=(d.events||[]).filter(e=>e.date===key).sort((a,b)=>(a.time||'').localeCompare(b.time||''));h+=`<button class="tend-cal-day ${inMonth?'':'mutedDay'} ${key===todayKey()?'today':''}" onclick="window.tendSelectDate('${key}')"><b>${dt.getDate()}</b><span>${ev.slice(0,3).map(e=>`<i>${esc(e.title)}</i>`).join('')}${ev.length>3?`<i>+${ev.length-3} more</i>`:''}</span></button>`}grid.innerHTML=h;renderEvents(d)}
  window.tendSelectDate=function(key){selected=key;const dt=new Date(key+'T12:00');cursor=new Date(dt.getFullYear(),dt.getMonth(),1);renderCalendar()};
  function renderEvents(d){const box=document.getElementById('tendEventList'),head=document.getElementById('tendSelectedTitle');if(!box||!head)return;head.textContent=new Date(selected+'T12:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});const list=(d.events||[]).filter(e=>e.date===selected).sort((a,b)=>(a.time||'').localeCompare(b.time||''));box.innerHTML=list.map(e=>`<div class="card tend-event"><div class="tend-event-time">${e.time||'All day'}</div><div style="flex:1"><b>${esc(e.title)}</b><div class="muted">${e.pet?esc((d.pets||[]).find(p=>p.id===e.pet)?.name||'Animal'):'Household / facility'}${e.notes?' · '+esc(e.notes):''}</div></div><button onclick="window.tendDeleteEvent(${e.id})">Delete</button></div>`).join('')||'<div class="empty">No events on this date. Add one with + Event. 📅</div>'}

  // Care: reliable check-offs plus real recurring tasks.
  function nextDate(date,repeat){const base=new Date((date||todayKey())+'T12:00');if(repeat==='daily')base.setDate(base.getDate()+1);else if(repeat==='every2days')base.setDate(base.getDate()+2);else if(repeat==='weekly')base.setDate(base.getDate()+7);else if(repeat==='biweekly')base.setDate(base.getDate()+14);else if(repeat==='monthly')base.setMonth(base.getMonth()+1);else if(repeat==='quarterly')base.setMonth(base.getMonth()+3);else return date||todayKey();return `${base.getFullYear()}-${String(base.getMonth()+1).padStart(2,'0')}-${String(base.getDate()).padStart(2,'0')}`}
  function repeatLabel(r){return ({daily:'Daily',every2days:'Every 2 days',weekly:'Weekly',biweekly:'Every 2 weeks',monthly:'Monthly',quarterly:'Every 3 months'})[r]||''}
  function fixCare(){const d=load();document.querySelectorAll('#careList .card.task .check').forEach(b=>{const id=b.dataset.careId;if(id)return;const card=b.closest('.task');const edit=card?.querySelector('button[onclick*="careForm"]');const m=edit?.getAttribute('onclick')?.match(/careForm\((\d+)\)/);if(m){b.dataset.careId=m[1];b.setAttribute('onclick',`window.tendToggleCare(${m[1]})`)}})}
  window.tendToggleCare=function(id){const d=load(),t=(d.care||[]).find(x=>x.id==id);if(!t)return;if(t.repeat&&t.repeat!=='none'){t.lastCompleted=t.date||todayKey();t.date=nextDate(t.date||todayKey(),t.repeat);t.done=false}else t.done=!t.done;save(d);setTimeout(()=>{fixCare();refreshDashboard()},0)};
  function careForm(existingId){const d=load(),t=existingId?d.care.find(x=>x.id==existingId):{};const repeat=t.repeat||'none';openCareModal(d,t,existingId,repeat)}
  function openCareModal(d,t,id,repeat){const modal=document.getElementById('modal'),body=document.getElementById('body');if(!modal||!body)return;body.innerHTML=`<h2>☑️ ${id?'Edit':'Add'} care task</h2><label>Task<input id="tendCareTitle" value="${esc(t.title||'')}" placeholder="Feed, clean stall, medication..."></label><div class="formgrid"><label>Due date<input id="tendCareDate" type="date" value="${t.date||todayKey()}"></label><label>Repeat<select id="tendCareRepeat"><option value="none" ${repeat==='none'?'selected':''}>Does not repeat</option><option value="daily" ${repeat==='daily'?'selected':''}>Daily</option><option value="every2days" ${repeat==='every2days'?'selected':''}>Every 2 days</option><option value="weekly" ${repeat==='weekly'?'selected':''}>Weekly</option><option value="biweekly" ${repeat==='biweekly'?'selected':''}>Every 2 weeks</option><option value="monthly" ${repeat==='monthly'?'selected':''}>Monthly</option><option value="quarterly" ${repeat==='quarterly'?'selected':''}>Every 3 months</option></select></label></div><label>Animal<select id="tendCarePet"><option value="">Facility / household</option>${(d.pets||[]).map(p=>`<option value="${p.id}" ${t.pet==p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><button class="primary" onclick="window.tendSaveCare(${id||'null'})">${id?'Save changes':'Save task'}</button>`;modal.classList.add('on')}
  window.tendSaveCare=function(id){const d=load();d.care=Array.isArray(d.care)?d.care:[];const title=document.getElementById('tendCareTitle')?.value.trim();if(!title)return alert('Give the care task a name first.');const date=document.getElementById('tendCareDate')?.value||todayKey(),repeat=document.getElementById('tendCareRepeat')?.value||'none',pet=document.getElementById('tendCarePet')?.value?Number(document.getElementById('tendCarePet').value):null;if(id!==null&&id!==undefined){const t=d.care.find(x=>x.id==id);if(!t)return alert('That care task could not be found.');Object.assign(t,{title,date,repeat,pet})}else d.care.push({id:Date.now(),done:false,title,date,repeat,pet});save(d);document.getElementById('modal')?.classList.remove('on');refreshDashboard();fixCare()};
  window.careForm=careForm;window.saveCare=window.tendSaveCare;

  // Dashboard: live stats and a focused Today view.
  function dashboardData(d){const today=todayKey(),open=(d.care||[]).filter(x=>!x.done),overdue=open.filter(x=>x.date&&x.date<today),todayTasks=open.filter(x=>!x.date||x.date===today),upcoming=open.filter(x=>x.date&&x.date>today).sort((a,b)=>a.date.localeCompare(b.date));const month=today.slice(0,7),monthEvents=(d.events||[]).filter(e=>e.date&&e.date.slice(0,7)===month);return {today,open,overdue,todayTasks,upcoming,monthEvents}};
  function ensureTodayUI(){const home=document.getElementById('home');if(!home||document.getElementById('tendTodayCard'))return;const stats=home.querySelector('.stats');if(!stats)return;const sec=document.createElement('div');sec.id='tendTodayCard';sec.className='card';sec.style.margin='0 0 14px';stats.after(sec)}
  function refreshDashboard(){const d=load(),x=dashboardData(d);ensureTodayUI();const statTasks=document.getElementById('statTasks'),statUpcoming=document.getElementById('statUpcoming');if(statTasks)statTasks.textContent=x.todayTasks.length+x.overdue.length;if(statUpcoming)statUpcoming.textContent=x.upcoming.length;const box=document.getElementById('tendTodayCard');if(box){const rows=x.todayTasks.map(t=>`<div class="tend-today-row"><button class="check" onclick="window.tendToggleCare(${t.id})">${t.done?'✓':''}</button><div style="flex:1"><b>${esc(t.title||'Care task')}</b><div class="muted">${t.pet?esc((d.pets||[]).find(p=>p.id==t.pet)?.name||'Animal'):'Household / facility'}${t.repeat&&t.repeat!=='none'?' · '+esc(repeatLabel(t.repeat)):''}</div></div><button onclick="window.careForm(${t.id})">Edit</button></div>`).join('');const overdue=x.overdue.map(t=>`<div class="tend-today-row tend-overdue"><button class="check" onclick="window.tendToggleCare(${t.id})">✓</button><div style="flex:1"><b>${esc(t.title||'Care task')}</b><div class="muted">Overdue · ${esc(t.date||'No date')}${t.pet?' · '+esc((d.pets||[]).find(p=>p.id==t.pet)?.name||'Animal'):''}</div></div><button onclick="window.careForm(${t.id})">Edit</button></div>`).join('');const ev=x.monthEvents.filter(e=>e.date>=x.today).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,3).map(e=>`<div class="tend-mini-event"><span>📅</span><div><b>${esc(e.title)}</b><div class="muted">${esc(e.date)}${e.time?' · '+esc(e.time):''}</div></div></div>`).join('');box.innerHTML=`<div class="tend-today-head"><div><b>🌿 Today</b><div class="muted">${new Date(x.today+'T12:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</div></div><span class="pill">${x.todayTasks.length} due</span></div>${overdue?`<div class="tend-today-label">⚠️ Overdue</div>${overdue}`:''}${rows?`<div class="tend-today-label">Today's care</div>${rows}`:''}${!rows&&!overdue?'<div class="muted" style="padding:8px 0">Nothing due today. Tiny victory. 🌱</div>':''}${ev?`<div class="tend-today-label">Next on your calendar</div>${ev}`:''}<button class="link" style="margin-top:6px" onclick="show('care')">See all care →</button>`}}

  // Money: exact cents math plus edit/delete controls.
  const cents=x=>{const n=Number(String(x??'').trim());return Number.isFinite(n)?Math.round(n*100):0};
  const money=n=>(Math.round(n)/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  function renderMoney(){
    const d=load(),box=document.getElementById('moneyList');if(!box)return;
    const total=(d.expenses||[]).reduce((sum,e)=>sum+cents(e.amount),0);
    const list=(d.expenses||[]).slice().reverse();
    box.innerHTML=`<div class="card" style="margin-top:0"><div class="muted">Total logged expenses</div><strong style="font-size:26px">$${money(total)}</strong><div class="muted" style="margin-top:4px">${list.length} expense${list.length===1?'':'s'} recorded</div></div>`+(list.length?list.map(x=>`<div class="card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div style="flex:1"><b>${esc(x.title||'Expense')}</b><div class="muted">${esc(x.date||'')}${x.cat?' · '+esc(x.cat):''}</div><strong>$${money(cents(x.amount))}</strong></div><div style="display:flex;gap:6px;flex-wrap:wrap"><button type="button" onclick="window.tendEditExpense(${x.id})">Edit</button><button type="button" onclick="window.tendDeleteExpense(${x.id})">Delete</button></div></div></div>`).join(''):'<div class="empty">No expenses yet.</div>');
  }
  function expenseForm(existing){const modal=document.getElementById('modal'),body=document.getElementById('body');if(!modal||!body)return;const e=existing||{};body.innerHTML=`<h2>💰 ${existing?'Edit':'Log'} expense</h2><label>Description<input id="tendExpenseTitle" value="${esc(e.title||'')}" placeholder="Hay, vet visit, bedding..."></label><div class="formgrid"><label>Amount<input id="tendExpenseAmount" type="number" inputmode="decimal" min="0" step="0.01" value="${e.amount??''}" placeholder="0.00"></label><label>Date<input id="tendExpenseDate" type="date" value="${e.date||todayKey()}"></label></div><label>Animal / category<input id="tendExpenseCat" value="${esc(e.cat||'')}" placeholder="Optional"></label><button class="primary" onclick="window.tendSaveExpense(${existing?e.id:'null'})">${existing?'Save changes':'Save expense'}</button>`;modal.classList.add('on')}
  window.tendSaveExpense=function(id){const d=load();d.expenses=Array.isArray(d.expenses)?d.expenses:[];const title=document.getElementById('tendExpenseTitle')?.value.trim(),rawAmt=document.getElementById('tendExpenseAmount')?.value.trim();if(!title)return alert('Give the expense a description first.');if(rawAmt===''||!Number.isFinite(Number(rawAmt))||Number(rawAmt)<0)return alert('Enter a valid expense amount.');const centsValue=cents(rawAmt),date=document.getElementById('tendExpenseDate')?.value||todayKey(),cat=document.getElementById('tendExpenseCat')?.value.trim()||'';if(id!==null&&id!==undefined){const e=d.expenses.find(x=>x.id==id);if(!e)return alert('That expense could not be found.');e.title=title;e.amount=(centsValue/100).toFixed(2);e.date=date;e.cat=cat}else d.expenses.push({id:Date.now(),title,amount:(centsValue/100).toFixed(2),date,cat});save(d);document.getElementById('modal')?.classList.remove('on');renderMoney();refreshDashboard()};
  window.tendEditExpense=function(id){const d=load(),e=(d.expenses||[]).find(x=>x.id==id);if(e)expenseForm(e);else alert('That expense could not be found.')};
  window.tendDeleteExpense=function(id){if(!confirm('Delete this expense?'))return;const d=load();d.expenses=(d.expenses||[]).filter(x=>x.id!=id);save(d);renderMoney();refreshDashboard()};

  function boot(){addUI();ensure();ensureTodayUI();fixCare();renderCalendar();renderMoney();refreshDashboard();window.expenseForm=expenseForm;const care=document.getElementById('careList');if(care)new MutationObserver(()=>{fixCare();refreshDashboard()}).observe(care,{childList:true,subtree:true});const moneyBox=document.getElementById('moneyList');if(moneyBox)new MutationObserver(()=>{if(!moneyBox.dataset.tendMoneyPatched){moneyBox.dataset.tendMoneyPatched='1';renderMoney()}}).observe(moneyBox,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();